name: Build Squirtle V1.4

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pi-gen dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qemu-user-static \
            binfmt-support \
            quilt \
            debootstrap \
            libarchive-tools \
            arch-test

      - name: Clone pi-gen and inject files
        run: |
          git clone https://github.com/RPi-Distro/pi-gen.git pi-gen

          # Inject config
          echo IMG_NAME=Squirtle > pi-gen/config
          echo DEPLOY_COMPRESSION=none >> pi-gen/config
          echo ENABLE_RECOMMENDED=0 >> pi-gen/config

          # Inject custom cleanup stage
          mkdir -p pi-gen/stage-tempclean
          echo '#!/bin/bash -e' > pi-gen/stage-tempclean/00-run.sh
          echo 'echo "🧼 Mid-stage cleanup running..."' >> pi-gen/stage-tempclean/00-run.sh
          echo 'apt-get clean' >> pi-gen/stage-tempclean/00-run.sh
          echo 'rm -rf /var/cache/apt/* /tmp/*' >> pi-gen/stage-tempclean/00-run.sh
          echo 'journalctl --rotate || true' >> pi-gen/stage-tempclean/00-run.sh
          echo 'journalctl --vacuum-time=1s || true' >> pi-gen/stage-tempclean/00-run.sh
          chmod +x pi-gen/stage-tempclean/00-run.sh

          #
