name: Build Squirtle V1.4

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pi-gen dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qemu-user-static \
            binfmt-support \
            quilt \
            debootstrap \
            libarchive-tools \
            arch-test

      - name: Clone pi-gen and inject files
        run: |
          git clone https://github.com/RPi-Distro/pi-gen.git pi-gen
          mkdir -p pi-gen/stage1/boot
          cp -r etc usr .github pi-gen/stage1/
          echo "boot setup skipped" | sudo tee pi-gen/stage1/boot/README.txt
          rm -rf pi-gen/stage5/00-install-libreoffice

          echo IMG_NAME=Squirtle > pi-gen/config
          echo DEPLOY_ZIP=0 >> pi-gen/config

      - name: Build the image
        run: |
          cd pi-gen
          sudo ./build.sh

      - name: Deep clean to free disk space before upload
        run: |
          sudo rm -rf pi-gen/work
          sudo rm -rf ~/.cache
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get clean
          sudo journalctl --rotate
          sudo journalctl --vacuum-time=1s

      - name: Upload raw image (.img)
        uses: actions/upload-artifact@v4
        with:
          name: squirtle-v1.4-output
          path: pi-gen/deploy/*.img
